---
ip: "192.168.33.10"
memory: 8192

authorize: ~/.ssh/id_rsa.pub

keys:
  - ~/.ssh/id_rsa

ports:
    http: 8000
    https: 4430

folders:
    - map: ~/Sites
      to: /var/www/html
      with: nfs
      options: ['actimeo=2']

wordpress:
  - site: default
    with:
      type: single
      title: Single-site WordPress Installation
      users:
        - admin:admin

  - site: multi
    with:
      type: multisite
      title: Multi-site WordPress Installation
      users:
        - admin:admin
